/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pbharut' at '8/25/16 11:03 AM' with Gradle 3.0
 *
 * @author pbharut, @date 8/25/16 11:03 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
